using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QAToolkit.Data;
using QAToolkit.Helpers;
using QAToolkit.Models;
using QAToolkit.Services;

namespace QAToolkit.Controllers
{
    [Authorize]
    public class HermesController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHermesService _hermes;

        public HermesController(ApplicationDbContext db, IHermesService hermes)
        {
            _db = db;
            _hermes = hermes;
        }

        public async Task<IActionResult> Index(int? chatId)
        {
            var userName = User.Identity!.Name!;

            var chats = await _db.HermesChats
                .Where(c => c.UserName == userName)
                .OrderByDescending(c => c.UpdatedAt ?? c.CreatedAt)
                .Take(30)
                .ToListAsync();

            HermesChat? activeChat = null;

            if (chatId.HasValue)
                activeChat = chats.FirstOrDefault(c => c.Id == chatId.Value);

            if (activeChat == null && chats.Any())
                activeChat = chats.First();

            ViewBag.Chats = chats;
            ViewBag.ActiveChat = activeChat;

            var recentActivity = await _db.HermesActivities
                .OrderByDescending(a => a.CreatedAt)
                .Take(20)
                .ToListAsync();

            ViewBag.RecentActivity = recentActivity;

            var userSettings = await _hermes.GetUserSettingsAsync(userName);
            ViewBag.HasApiKey = !string.IsNullOrWhiteSpace(userSettings?.ApiKey);
            ViewBag.UserProvider = userSettings?.Provider ?? "Groq";

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewChat()
        {
            var chat = new HermesChat
            {
                UserName = User.Identity!.Name!,
                Title = "New Chat",
                CreatedAt = DateTimeHelper.BdNow
            };
            _db.HermesChats.Add(chat);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { chatId = chat.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Messages(int chatId)
        {
            var userName = User.Identity!.Name!;
            var chat = await _db.HermesChats.FindAsync(chatId);
            if (chat == null || chat.UserName != userName) return NotFound();

            var messages = await _db.HermesMessages
                .Where(m => m.ChatId == chatId)
                .OrderBy(m => m.CreatedAt)
                .ToListAsync();

            return Json(messages.Select(m => new { m.Role, m.Content, CreatedAt = m.CreatedAt.ToString("HH:mm") }));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Send(int chatId, [FromForm] string message)
        {
            if (string.IsNullOrWhiteSpace(message))
                return Json(new { success = false, error = "Empty message." });

            var userName = User.Identity!.Name!;
            var chat = await _db.HermesChats.FindAsync(chatId);
            if (chat == null || chat.UserName != userName)
                return Json(new { success = false, error = "Chat not found." });

            try
            {
                var reply = await _hermes.ChatAsync(userName, chatId, message.Trim());
                return Json(new { success = true, reply, chatTitle = chat.Title });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveScript([FromForm] string name, [FromForm] string content, [FromForm] string? tags, [FromForm] string? description)
        {
            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(content))
                return Json(new { success = false, error = "Name and content are required." });

            var script = new PlaywrightScript
            {
                Name = name.Trim(),
                Description = string.IsNullOrWhiteSpace(description) ? "Generated by Hermes" : description.Trim(),
                Tags = string.IsNullOrWhiteSpace(tags) ? null : tags.Trim(),
                ScriptContent = content,
                FileExtension = ".js",
                RunMode = "node",
                IsPublic = false,
                CreatedBy = User.Identity!.Name,
                CreatedAt = DateTimeHelper.BdNow
            };

            _db.PlaywrightScripts.Add(script);
            await _db.SaveChangesAsync();

            await _hermes.LogActivityAsync("ScriptCreated", User.Identity!.Name!, script.Id, script.Name, script.Tags, "via Hermes");

            return Json(new { success = true, scriptId = script.Id, scriptName = script.Name });
        }

        [HttpGet]
        public async Task<IActionResult> GetSettings()
        {
            var settings = await _hermes.GetUserSettingsAsync(User.Identity!.Name!);
            return Json(new
            {
                provider = settings?.Provider ?? "Groq",
                hasKey = !string.IsNullOrWhiteSpace(settings?.ApiKey),
                model = settings?.Model ?? ""
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveSettings([FromForm] string provider, [FromForm] string apiKey, [FromForm] string? model)
        {
            if (string.IsNullOrWhiteSpace(apiKey))
                return Json(new { success = false, error = "API key is required." });

            await _hermes.SaveUserSettingsAsync(User.Identity!.Name!, provider, apiKey, model);
            return Json(new { success = true });
        }

        [HttpGet]
        public async Task<IActionResult> Activity()
        {
            var activities = await _db.HermesActivities
                .OrderByDescending(a => a.CreatedAt)
                .Take(30)
                .ToListAsync();

            return Json(activities.Select(a => new
            {
                a.UserName,
                a.ActivityType,
                a.EntityName,
                a.Tags,
                a.Extra,
                CreatedAt = a.CreatedAt.ToString("MMM dd HH:mm")
            }));
        }
    }
}
